### ISSUE TITLE
Keep it up!!!

### ISSUE THREAD

**Issue by edysegura** [sandrooliveira/advanced-css-course#1]
Keep it up @sandrooliveira !!!! Together we are better!

**Comment by edysegura** [comment]
As you did this commit https://github.com/sandrooliveira/advanced-css-course/commit/938f876863d55c98284dc08778e48c2a04da2efd I will close this! But be aware that I'm watching you!

**Comment by sandrooliveira** [comment]
haha Thank you for encouraging me Edy!

**Comment by edysegura** [comment]
Don't forget to do at least one commit today!
