### ISSUE TITLE
The secret is the frequency

### ISSUE THREAD

**Issue by edysegura** [sandrooliveira/advanced-css-course#2]
Hi @sandrooliveira!! The frequency is the key doesn't matter if it takes 5mins or 1 hour it just needs to be every day!

**Comment by edysegura** [comment]
![image](https://user-images.githubusercontent.com/5324414/43493276-85a66ad2-9503-11e8-920b-8ada5dc913f6.png)

**Comment by sandrooliveira** [comment]
I am busy lately, but I have created an issue to myself.
https://github.com/sandrooliveira/advanced-css-course/issues/3 :)
